### ISSUE TITLE
α-4 známky

### ISSUE THREAD

**Issue by ghost** [CutoNaito/alfa4#1]
Vážený CutoNaito,

dovolte mi, abych Vám poslal tento e-mail k hodnocení Vašeho projektu. S potěšením Vám oznamuji, že jste dosáhl skóre 4 na svém projektu. Chci Vám poděkovat za pečlivou práci, kterou jste vložil do tohoto projektu, a gratuluji Vám k dosaženému úspěchu.

Věřím, že tento úspěch bude pro Vás motivací k dalšímu rozvoji a nadále se budete snažit dosahovat svých cílů.

S pozdravem,
Ondřej Mandík

**Comment by CutoNaito** [comment]
wohoo
